#!groovy

// Generated by IBM TransformationAdvisor
// Wed Nov 27 18:37:31 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}